### ISSUE TITLE
Tetris AI

### ISSUE THREAD

**Issue by michiel2005** [djoamersfoort/lichtkrant#38]
Is it possible that I can add a ai that plays tetris when the lichtkrant is in it's idle state? And is it possible to test the code on a computer without uploading it to the lichtkrant?

**Comment by wipeautcrafter** [comment]
In de [readme](https://github.com/djoamersfoort/lichtkrant#readme) staat hoe je het programma in "display" mode kan draaien. Hiermee is het mogelijk om de lichtkrant in je terminal te previewen. Verder kan je voor het toevoegen van een Tetris AI een pull request maken.
